version: '2'
services:
    # Raspberry Pi Jenkins
    jenkins:
        image: tanisperez/raspberrypi-jenkins:1.0-arm64
        container_name: jenkins
        volumes:
         - /mnt/data/jenkins:/var/jenkins_home
	 - /var/run/docker.sock:/var/run/docker.sock
	 - /usr/bin/docker:/usr/bin/docker
	 - /etc/timezone:/etc/timezone
	 - /etc/localtime:/etc/localtime
        ports:
            - 8080:8080
            - 50000:50000
        restart:
            always
